require('./start');
require('./contactus');
require('./my_doctor');
require('./specialities');
require('./doctors_list');
require('./doctor_detail');
require('./call_doctor');
require('./register');
require('./charge');
require('./back');
// require('./payment_return');
require('./test_answer');
// require('./prevent_replay');
