require('./ask_question');
require('./contactus');
require('./doctor_answer');
require('./quiz');
require('./refer');
require('./register_doctor');
require('./show_no_answer_question');
require('./specialities');
require('./start');
require('./errorHandling')
