require('./state/start');
require('./state/refer');
require('./state/register_doctor');
require('./state/specialities');
require('./state/ask_question');
// require('./state/contactus');
// require('./state/my_doctor');
// require('./state/search_doctor_with_name');
// require('./state/search_doctor_with_code');
// require('./state/doctor_detail');
// require('./state/call_doctor');
// require('./state/register');
// require('./state/charge');
// require('./state/back');
// require('./state/payment_return');
// require('./state/test_answer');
// require('./state/prevent_replay');
